function aa(h,b,g,c,f){function q(a,d){w=w.replace(y[a],"&dbg"+a+"="+d)}function t(a,d){if(a instanceof Array){for(var e=0,m=a.length;e<m;e++)a[e]=a[e]+"="+d;return"&"+a.join("&")}return"&"+a+"="+d}var k=new H,p=f&&f.dvObj||window.$dv,u=f&&"undefined"!==typeof f.billable||p&&p.tags[$uid]&&p.tags[$uid].billable,r=f&&f.impressionId||window.$uid,l=window.Jf||c,n=Array(l.eb),a=l.Wa/l.Zb+1,d=null,m="";h=h?h:null;g=g?g:"";var e="",x=null,z=0,P=new RegExp(/&strp=[^&]*/),S=new RegExp(/&narme=[^&]*/),T=new RegExp(/&narm=[^&]*/),
da=new RegExp(/&naral=[^&]*/),ea=new RegExp(/&evid=[^&]*/);c=new RegExp(/&jsver=[^&]*/);for(var U=new RegExp(/&vct=[^&]*/),y=[new RegExp(/&dbg0=[^&]*/),new RegExp(/&dbg1=[^&]*/),new RegExp(/&dbg2=[^&]*/),new RegExp(/&dbg3=[^&]*/),new RegExp(/&dbg4=[^&]*/),new RegExp(/&dbg5=[^&]*/),new RegExp(/&dbg6=[^&]*/),new RegExp(/&dbg7=[^&]*/),new RegExp(/&dbg8=[^&]*/),new RegExp(/&dbg9=[^&]*/),new RegExp(/&dbg10=[^&]*/),new RegExp(/&dbgtx=[^&]*/)],fa=[new RegExp(/&b0=[^&]*/),new RegExp(/&b1=[^&]*/),new RegExp(/&b2=[^&]*/),
new RegExp(/&b3=[^&]*/),new RegExp(/&b4=[^&]*/),new RegExp(/&b5=[^&]*/),new RegExp(/&b6=[^&]*/),new RegExp(/&b7=[^&]*/),new RegExp(/&b8=[^&]*/),new RegExp(/&b9=[^&]*/),new RegExp(/&b10=[^&]*/),new RegExp(/&b11=[^&]*/)],Y=Array(l.eb),v={da:{D:null,F:null,A:null,v:null,Ie:!1},j:{u:null,s:null,G:null,H:null,B:null,C:null,o:null,m:null,Ie:!1},Za:{ub:null,tb:null},Bb:0},I="",J="",D,E,K="",L="",M=!1,F="",V=0;V<l.eb;V++)Y[V]="&b"+V+"=";b=function(a,d){if(a&&d)return d.replace(new RegExp(a+"=\\d*[&^#]"),
"")}("prndr",b?b:null);var G=g+"?"+b,G=c.test(G)?G.replace(c,"&jsver="+h):G+"&jsver="+h,w="&naral=&narm=&narme=&dbg2=&dbg3=&dbg4=&dbg5=&dbg6=&dbg7=&dbg8=&dbg9=&dbg10=&dbgtx=&vct=",A="&strp=";b="&ctime="+(new Date).getTime();var N=0,Q="",O="",R=0,B=0,C=0,W=0;this.Qc=function(){return N};this.Jc=G+A+w+b+e+I;setEventId=function(a){x=a;w=w.replace(ea,"&evid="+x)};setNAPReason=function(a){O=O+a.slice(0,500)};setAdLocatorIndicator=function(a){R=R|a;w=w.replace(da,"&naral="+R)};setNAPMeasure=function(a){k.a("l2("+
a+")");B=B|a;ga()?(setNotApplicableTime(),N=0):0==N&&(N=(new Date).getTime());w=w.replace(T,"&narm="+B);k.a("l2e")};setNAPMeasureErr=function(a){C=C|a;w=w.replace(S,"&narme="+C)};this.od=function(a){W=W|a;w=w.replace(U,"&vct="+W)};setBuckectStr=function(a,d){d?e=e.replace(fa[a],"&b"+a+"="+n[a]):e=e+"&b"+a+"="+n[a]};setNotApplicableTime=function(){0!=N&&(Q=(new Date).getTime()-N)};getBucketString=function(){return e};getFraudNonFraudEvents=function(a,d,e){return M?t(d,e):t(a,e)};this.jc=function(){return M};
this.nd=function(a){d=a;A=A.replace(P,"&strp="+d);this.nd=function(){}};this.jb=function(){return(new Date).getTime()};var ha=this.jb();this.ue=function(){return ha};this.rf=function(){M=!0};this.pf=function(a,d){F+="&"+d.reportQueryString.viewrate+"="+a[d.serverProperties.viewedRate]+"&"+d.reportQueryString.error+"="+a[d.serverProperties.error]+"&"+d.reportQueryString.projected+"="+(1==a[d.serverProperties.viewed]?2:a[d.serverProperties.projected]);if("undefined"===typeof a[d.serverProperties.featurebit]||
a[d.serverProperties.featurebit]&&1==a[d.serverProperties.featurebit])F+="&"+d.reportQueryString.measurems+"=0",1==a[d.serverProperties.viewed]&&(F+="&"+d.reportQueryString.viewedms+"=0")};this.cf=function(){B=B&-3;C=C&-2;C&=-3};this.wb=function(){setNAPMeasure(2)};this.mf=function(){setNAPMeasureErr(8);this.qc()};this.qc=function(){setNAPMeasure(4)};this.jd=function(){setAdLocatorIndicator(8);this.wb()};this.ud=function(a){setAdLocatorIndicator(16);q(9,a)};this.vd=function(){setAdLocatorIndicator(1)};
this.kf=function(){this.wb();setNAPMeasureErr(1)};this.jf=function(){this.wb();setNAPMeasureErr(2)};this.pc=function(a){setNAPMeasure(8);setNAPReason(a)};this.ff=function(){k.a("l1");B=B&-3;setNAPMeasure(1);k.a("l1e")};this.md=function(){setNAPMeasure(16)};this.ke=function(){return n};this.kd=function(d,e){k.a("ie15");if(0<=d.i){var m=Math.floor(d.i/l.Zb);0<d.i%l.Zb?m++:0<d.i&&m++;isNaN(n[m])&&(n[m]=0);n[m]+=e;d.K&&m>=a||0==d.K&&6<=m?z+=e:z=0}k.a("ie15e")};this.we=function(){for(var a=0,d=0;d<n.length;d++)n[d]&&
(a+=n[d]);return a};this.hf=function(a){var d=M?"false":a.Yc;a="&advisonl="+(null==a.Yc?"":d)+("&adabvvponl="+(null==a.Xc?"":a.Xc));q(8,"CSS1Compat"===document.compatMode?1:0);k.a("ff52");void 0!=document.documentMode&&null!=document.documentMode&&q(10,document.documentMode);k.a("ff52e");I=a};this.$a=function(a){k.a("ie14");L="&adbtftopg="+(null==a?"":M?"true":a)};this.gf=function(a){null!=a&&(v=a)};this.ld=function(a){k.a("ie19");this.gf(a.L);this.qf();k.a("ie19e")};this.yd=function(){var a;a="&vptoscrx="+
(null!=v.da.D?Math.round(v.da.D):"");a+="&vptoscry="+(null!=v.da.F?Math.round(v.da.F):"");a+="&vpwdth="+(null!=v.da.A?Math.round(v.da.A):"");a+="&vphgt="+(null!=v.da.v?Math.round(v.da.v):"");a+="&adtovpx="+(null!=v.j.u?Math.round(v.j.u):"");a+="&adtovpy="+(null!=v.j.s?Math.round(v.j.s):"");a+="&adtopgx="+(null!=v.j.G?Math.round(v.j.G):"");a+="&adtopgy="+(null!=v.j.H?Math.round(v.j.H):"");a+="&adtoscrx="+(null!=v.j.B?Math.round(v.j.B):"");a+="&adtoscry="+(null!=v.j.C?Math.round(v.j.C):"");a+="&scrwdth="+
(null!=v.Za.ub?Math.round(v.Za.ub):"");a+="&scrhgt="+(null!=v.Za.tb?Math.round(v.Za.tb):"");return a+="&almesind="+v.Bb};this.zd=function(){var a="";if(D&&E){var d=null!=v.j.o?v.j.o:null,e=null!=v.j.m?v.j.m:null;0>D*E&&(a+="&dvp_adwdth="+D,a+="&dvp_adhgt="+E,D=d,E=e)}else D=null!=v.j.o?v.j.o:null,E=null!=v.j.m?v.j.m:null;a+="&adwdth="+(null!=D?D:"");return a+="&adhgt="+(null!=E?E:"")};this.qf=function(){setNotApplicableTime();e="";for(var a=0;a<n.length;a++)n[a]&&(e+=Y[a]+n[a]);J=this.zd();K=I+this.yd()+
J;K+=L;this.Jc=G+A+w+e+K};this.Oc=function(){return 1E3<=z};this.ca=function(a){var d=G+"&impid="+r,l=-1,b=k.mb();p&&p.tags[r]&&p.tags[r].getTimeDiff&&(l=p.tags[r].getTimeDiff());switch(a){case 1:m=l;d+=A+w+"&napt="+Q+K+b+"&napr="+O;b="";u&&(b=f.Va?getFraudNonFraudEvents(["isbmms"],"isfbmms",l):getFraudNonFraudEvents(["isbmms","isgmmims"],"isfbmms",l));d+=b+getFraudNonFraudEvents("ismms","isfmms",l)+"&isumms="+l;break;case 2:d+=A+w+"&napt="+Q+K+b+"&napr="+O+getFraudNonFraudEvents("isnmms","isfnmms",
l);break;case 3:d+="&istoms="+l;case 4:case 8:d+=A+L+J+"&isbxdms="+l+(M?"&fbxdtb="+this.we():e);break;case 5:m=m||l;d+=A+L+J+I+getFraudNonFraudEvents("isiabvms","isfiabvms",l)+"&isuiabvms="+l+getFraudNonFraudEvents("ismms","isfmms",m)+"&isumms="+m;break;case 6:m=m||l;d+=L+J+I+getFraudNonFraudEvents("iscvmvms","isfcvmvms",l)+getFraudNonFraudEvents("ismms","isfmms",m);break;case 16:d+=A+w+"&napt="+Q+b+"&napr="+O+"&ishems="+l;break;case 7:return d;case 9:d+=F;break;case 10:d+="&ismms=0";break;case 17:m=
m||l;b=f.Va?["isbmms"]:["isbmms","isgmmims"];d+=A+L+J+I+getFraudNonFraudEvents(f.Va?["isbvms"]:["isbvms","isgmpims"],"isfbvms",l)+getFraudNonFraudEvents(b,"isfbmms",m);break;default:d=this.Jc+"&napt="+Q+"&ctime="+this.jb()+b+"&napr="+O}return d+"&evid="+a+"&ctime="+this.jb()};this.je=function(){k.a("ie17");for(var a=[],d=0;d<l.eb;d++)a[d]=n[d]?n[d]:0;return a};var ga=this.Rb=function(){return 2==(B&2)&&8!=(R&8)||4==(B&4)||8==(C&8)&&8==(R&8)?!1:!0};this.Ye=function(a){k.a("l3");a=k.na(a);k.a("cm3e");
a&&(q(5,a.w),q(6,a.h));k.a("l3e")};return this}
function ba(h,b){this.window=null;this.hb={};this.images={};this.Ub=function(b){var c=this.window.document.createElement("img");c.name=c.id=b;c.width=0;c.height=0;c.style.display="none";c.src="";this.window.document.body.insertBefore(c,this.window.document.body.firstChild);return c};this.sc=function(b,c){if(c&&1!=this.hb[c]||16==c)this.images[c].src=b,this.hb[c]=1};this.$=function(b,c){if(c&&1!=this.hb[c]||16==c||7==c)this.window.document.createElement("img").src=b,this.hb[c]=1};if(this.window=h)this.images=
{3:this.Ub(b+"_13"),4:this.Ub(b+"_14"),8:this.Ub(b+"_18")};return this}function X(){this.sc=function(){};this.$=function(){}}
function ca(h,b,g,c){function f(){if(1==x){try{for(var d in m)e.removeChild(m[d]);a.document.body.removeChild(e)}catch(l){}x=!1}}function q(a){a=a||0;var d=p(0);d.ad()?7<d.lb()?(f(),P=z=x=!1):(x=!0,z=!1):20>a?(a++,setTimeout(q,50,a)):(x=z=P=!1,f())}function t(a){$dv&&$dv.tags&&$dv.tags[c]&&$dv.tags[c].getTimeDiff&&$dv.tags[c].getTimeDiff();if(null!==a.cb)for(var d=0;d<a.cb.length;d++){var e=p(d).lb();0==d?e>S&&(S=e):e>T&&(T=e)}}function k(a){for(var d=!0,e=0;13>=e;e++)var m=p(e),d=d&(null!==m&&m.ad());
if(!d)return null;a.Ec=0;a.mc=0;a.lc=0;a.gc=0;a.Ca=0;a.cb=Array(13);d=p(0).lb();for(e=1;13>=e;e++)if(m=5<Math.abs(p(e).lb()-d),a.cb[e]=m)switch(a.Ec++,e){case 2:case 3:case 4:case 5:a.mc++;break;case 6:case 7:case 8:case 9:a.lc++;break;case 10:case 11:case 12:case 13:a.gc++}if(13===a.Ec)return a.Ca=100,t(a),!0;d=a.cb;if(!1===d[1]){if(3<=a.gc||3<=a.lc||3<=a.mc)return t(a),null;a.Ca=0;t(a);return!1}if(!0===d[1]&&(!0===d[2]&&!0===d[3]||!0===d[2]&&!0===d[4]||!0===d[3]&&!0===d[5]||!0===d[4]&&!0===d[5])||
!0===d[1]&&4==a.lc||!0===d[1]&&4==a.gc&&1<=a.mc)return a.Ca=50,t(a),!0;if(d[2]&&d[5]&&!(d[6]&&d[10]&&d[1]&&d[13]&&d[9])||d[4]&&d[3]&&!(d[8]&&d[12]&&d[1]&&d[11]&&d[7]))return t(a),null;a.Ca=0;t(a);return!1}function p(a){a=m[a];var d=null;a&&(d=a.contentWindow);return d}function u(){for(var a=d.getBoundingClientRect(),e=a.width,b=a.height,r=e/(1+l),c=b/(1+l),u=e/l,g=b/l,k=0;13>=k;k++){var n=a.left,f=a.top;switch(k){case 0:f=n=-1E5;break;case 1:n+=(e-1)/2;f+=(b-1)/2;break;case 3:n+=e-1;break;case 4:f+=
b-1;break;case 5:n+=e-1;f+=b-1;break;case 6:n+=(e-u)/2;f+=(b-g)/2;break;case 7:n+=(e-u)/2+u;f+=(b-g)/2;break;case 8:n+=(e-u)/2;f+=(b-g)/2+g;break;case 9:n+=(e-u)/2+u;f+=(b-g)/2+g;break;case 10:n+=(e-r)/2;f+=(b-c)/2;break;case 11:n+=(e-r)/2+r;f+=(b-c)/2;break;case 12:n+=(e-r)/2;f+=(b-c)/2+c;break;case 13:n+=(e-r)/2+r,f+=(b-c)/2+c}6<=k&&(n-=.5,f-=.5);var x=m[k];x.style.left=n+"px";x.style.top=f+"px"}}function r(){if(null!=d&&null!=d.parentNode){z=!0;e=a.document.createElement("div");a.document.body.appendChild(e);
for(var l=0;13>=l;l++){var b=a.document.createElement("iframe");b.width=1;b.height=1;b.style.position="absolute";b.frameBorder="0";b.style.visibility="hidden";b.style.zIndex=-9999999;b.style.display="block";b.src="javascript:no=false;yes=true;("+function(){window.Pe={Vd:100};window.Lc=no;window.bb=0;window.Mc=0;window.Vc=0;window.Kf=no;window.lb=function(){return window.Vc};window.ad=function(){return window.Lc};window.Oe=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||
window.msRequestAnimationFrame;window.Qb=function(){window.bb++;window.Oe(window.Qb,document)};window.Qb();setInterval(function(){10>window.bb&&window.Qb();window.Vc=window.bb-window.Mc;window.Mc=window.bb},window.Pe.Vd);window.setTimeout(function(){window.Lc=yes},250)}.toString()+")();";e.appendChild(b);m.push(b)}u()}}var l=Math.sqrt(2),n=new H,a=null,d=null,m=[],e,x=!1,z=!1,P=n.rb(h,b,g),S=0,T=0;this.Ge=function(){0==z&&(0==(this.Ua()&&(null!=d&&n.Zc(d,a)?!0:!1))?x=!1:(r(),q()))};this.Ua=function(){return P};
this.Le=function(){return x};this.pd=function(e,m){a=e;d=m;this.Ge()};this.ye=function(){if(0==x)return null;var a={};return null==k(a)?null:a.Ca}}
function ia(h,b,g,c,f,q,t,k){this.b=new H;this.window=h;this.f=b;this.M=g;this.I=c;this.W=t&&t.Enums.BrowserId||window.$dv.Enums.BrowserId;this.X=t&&t.Enums.TrafficScenario||window.$dv.Enums.TrafficScenario;this.P=f;this.ec=q;this.fa=null;this.fa=new ca(this.M,this.I,t,k);null!=this.fa&&this.fa.Ua()&&this.fa.pd(this.window,this.f);this.nb=this.sb=this.ra=null;this.ob=!1;var p=0;this.ia={Ld:1,Md:2,Fd:4,Hb:8,Ed:16,Ib:32,Kd:64};this.oc=function(b,r,l,c){if(c&&c.insertBefore&&c.firstChild&&(b=this.window.document.createElement(b))){for(var a in r)b[a]=
r[a];for(a in l)b.style[a]=l[a];c.insertBefore(b,c.firstChild);return b}return null};this.ac=function(b,c,l){var n=c.A;c=c.v;var a=0,d=0,m=b.right-b.left,e=b.bottom-b.top;if(0>b.bottom||0>b.right||b.top>c||b.left>n||0>=m||0>=e)return 0;0>b.top?Math.abs(b.top)>=e?a=e:(a=e+b.top,a>c&&(a=c)):a=b.top+e>c?c-b.top:e;0>b.left?Math.abs(b.left)>=m?d=m:(d=m+b.left,d>n&&(d=n)):d=b.left+m>n?n-b.left:m;return 0>=d||0>=a?0:Math.round(d*a/(m*e)*(l?m*e/((l.right-l.left)*(l.bottom-l.top)):1)*100)};this.$b=function(b,
c){try{var l={x:b.offsetLeft,y:b.offsetTop};if(b.offsetParent){var n=this.$b(b.offsetParent,c);l.x+=n.x;l.y+=n.y}else c!=c.parent&&this.b.Jb(c,c.parent)&&(n=this.$b(c.frameElement,c.parent),l.x+=n.x,l.y+=n.y);return l}catch(a){return{x:null,y:null}}};this.oa=function(b){if(this.M==this.X.CrossDomain)if(this.b.wa(this.window)&&this.window.$sf.ext.geom)this.oa=function(){var a=this.window.$sf.ext.geom(),d=window.outerHeight||this.window.document.documentElement.clientHeight?this.window.outerHeight-
parseInt(a.win.h):this.P.Explorer.Y,m={A:null,v:null,D:null,F:null,g:!1};m.A=parseInt(a.win.w);m.v=parseInt(a.win.h);m.D=parseInt(a.win.l);m.F=parseInt(a.win.t)+d;m.g=!0;return m};else if(this.I.V==this.W.Firefox)this.oa=function(){var a=8==screen.top-this.window.screenY&&8==screen.left-this.window.screenX,d=a?0:this.window.screenX-screen.left,a=a?0:this.window.screenY-screen.top,m={A:null,v:null,D:null,F:null,g:!1};m.A=this.window.outerWidth;m.v=this.window.outerHeight-this.P.Firefox.Y;m.D=d;m.F=
a+this.P.Firefox.Y;m.g=!0;return m};else if(this.b.ic(this.window)){var c=this;this.window.context.observeIntersection(function(a){a.forEach(function(a){c.ra=a})});this.oa=function(){var a={A:null,v:null,g:!1,D:null,F:null};null!=this.ra?(a.A=this.ra.rootBounds.width,a.v=this.ra.rootBounds.height):(a.A=0,a.v=0);a.g=!0;return a}}else if(this.I.V==this.W.IE&&/^[11|12]/.test(this.I.va))this.oa=function(){var a=-8==this.window.screenY&&-8==this.window.screenX,d=a?0:this.window.screenX,a=a?0:this.window.screenY,
m={A:null,v:null,D:null,F:null,g:!1};m.A=this.window.outerWidth;m.v=this.window.outerHeight-this.P.Explorer.Y;m.D=d;m.F=a+this.P.Explorer.Y;m.g=!0;return m};else if(this.I.V==this.W.IE&&/[6-9]|[10]/.test(this.I.va)){var l=this.oc("iframe",{name:"dv_ie9onload",src:"",width:0,height:0,de:0,Qe:"0",Re:"0"},{display:"inline",position:"absolute",top:0,left:0,wf:"none",zIndex:0,border:0},this.window.document.body),n=this.oc("iframe",{name:"dv_ie9onmousemove",src:"",width:0,height:0,de:0,Qe:"0",Re:"0"},{display:"inline",
position:"absolute",top:0,left:0,wf:"none",zIndex:0,border:0},this.window.document.body),a=n.contentWindow||n.window||n.contentDocument.window||n.contentWindow.window||this.window.zf,d=l.contentDocument||l.contentWindow.document,l=n.contentDocument||n.contentWindow.document,m="<html><head><script >window.onload = "+function(a){a&&(window.event=a);isFinite(String(window.event.clientY))&&(parent.Qa={Mb:window.event.clientY,Lb:window.event.clientX,xd:window.event.screenY-window.event.clientY-window.screenY})}.toString()+
"; \x3c/script></head><body></body></html>",n='<html><head></head><body><script > function runMoM(){ window.document.body.fireEvent("onmousemove");} window.document.body.onmousemove = '+function(a){a&&(window.event=a);isFinite(String(window.event.clientY))&&(parent.sa={Mb:window.event.clientY,Lb:window.event.clientX,Fa:window.event.screenY-window.event.y,Ea:window.event.screenX-window.event.x})}.toString()+"; runMoM();\x3c/script></body></html>";l.open("text/html","replace");l.write(n);l.close();
d.open("text/html","replace");d.write(m);d.close();("CSS1Compat"===document.compatMode?this.window.document.documentElement:this.window.document.body).clientLeft;this.oa=function(){a.runMoM();d.open("text/html","replace");d.write(m);d.close();var e=this.window.sa,b=this.window.Qa,l=screen.availWidth,c=screen.availHeight,b=b?b.xd:this.P.Explorer.Y;if(e){var n=e.Ea,f=e.Fa;e.Ea>=l&&(e.Ea-=l);e.Fa>=c&&(e.Fa-=c);var r={A:null,v:null,D:null,F:null,g:!1};r.A=this.window.outerWidth?this.window.outerWidth-
20:l-e.Ea-20;r.v=this.window.outerHeight?this.window.outerHeight-b-10:c-e.Fa-10;r.D=n;r.F=f;r.g=!0}else r={A:null,v:null,D:null,F:null,g:!1},r.A=this.window.outerWidth?this.window.outerWidth-20:l-20,r.v=this.window.outerHeight?this.window.outerHeight-b-10:c-10,r.D=null,r.F=null,r.g=!1;return r}}else this.b.qb()?(this.gd(),this.oa=function(){this.ob||this.gd();var a={A:null,v:null,D:null,F:null,g:!1};a.A=this.window.outerWidth;a.v=this.window.outerHeight-this.P.Chrome.Y;a.g=!1;return a}):this.oa=this.I.V==
this.W.Chrome?function(){var a={A:null,v:null,D:null,F:null,g:!1},d=!1;try{a.A=this.window.frameElement.offsetParent.parentNode.clientWidth,a.v=this.window.frameElement.offsetParent.parentNode.clientHeight,d=!0}catch(m){}a.D=this.window.screenX;a.F=this.window.screenY;a.g=d;return a}:null!=this.fa&&this.fa.Ua()?function(){var a={A:null,v:null,D:null,F:null,g:!1};a.A=this.window.outerWidth;a.v=this.window.outerHeight-this.P.Safari.Y;a.g=!1;return a}:function(){return{A:null,v:null,D:null,F:null,g:!1}};
else this.oa=function(){var a,d,m=this.window.top;void 0!=m.mozInnerScreenX&&null!=m.mozInnerScreenX?(a=m.mozInnerScreenX,d=m.mozInnerScreenY):void 0!=m.screenX&&null!=m.screenX?0!=m.screenLeft+8&&m.screenLeft+8!=screen.width||0!=m.screenTop+8&&m.screenTop+8!=screen.height?(a=m.screenLeft,d=m.screenTop+(m.outerHeight-m.innerHeight)):(a=m.screenLeft+8,d=m.screenTop+(m.outerHeight-m.innerHeight)+8):(a=m.screenLeft,d=m.screenTop);var b={A:null,v:null,D:null,F:null,g:!1},l=this.b.Sa(m);b.A=m.innerWidth||
l.clientWidth;b.v=m.innerHeight||l.clientHeight;b.D=a;b.F=d;b.g=!0;return b};return this.oa(b)};this.ma=function(b,c){p=1;this.M==this.X.CrossDomain?this.b.wa(this.window)&&this.window.$sf.ext.geom&&this.window.$sf.ext.geom().par?(p=8,this.ma=function(){var b=this.window.$sf.ext.geom(),c=window.outerHeight||this.window.document.documentElement.clientHeight?this.window.outerHeight-parseInt(b.win.h):this.P.Explorer.Y,a={u:null,s:null,G:null,H:null,B:null,C:null,o:null,m:null,g:!1,rect:null,N:null,qa:null};
a.u=parseInt(b.self.l)-parseInt(b.par.l);a.s=parseInt(b.self.t)-parseInt(b.par.t);a.G=parseInt(b.self.l);a.H=parseInt(b.self.t);a.B=parseInt(b.win.l)+a.u;a.C=parseInt(b.win.t)+a.s+c;a.o=parseInt(b.self.w);a.m=parseInt(b.self.h);a.g=!0;a.rect={top:a.s,bottom:a.s+a.m,left:a.u,right:a.u+a.o};return a}):this.I.V==this.W.Firefox?this.ma=function(){var b=1;window.devicePixelRatio&&(b=window.devicePixelRatio);var c=this.window.screenX,a=this.window.screenY,d=this.window.mozInnerScreenX/b-c,b=this.window.mozInnerScreenY/
b-a-this.P.Firefox.Y,d={left:d,top:b,right:d+this.window.innerWidth,bottom:b+this.window.innerHeight},b={u:null,s:null,G:null,H:null,B:null,C:null,o:null,m:null,g:!1,rect:null,N:null,qa:null};b.u=d.left;b.s=d.top;b.G=null;b.H=null;b.B=c+d.left;b.C=a+d.top;b.o=this.window.innerWidth;b.m=this.window.innerHeight;b.g=!0;b.rect=d;this.b.Ab()&&(b=this.ib(b));return b}:this.b.ic(this.window)?(p=32,this.ma=function(){var b={u:null,s:null,o:null,m:null,g:!1,rect:null,N:null,qa:null,G:null,H:null,B:null,C:null};
null!=this.ra?(b.u=this.ra.boundingClientRect.left,b.s=this.ra.boundingClientRect.top,b.o=this.ra.boundingClientRect.width,b.m=this.ra.boundingClientRect.height):(b.u=0,b.s=0,b.o=0,b.m=0);b.g=!0;b.rect={top:b.s,bottom:b.s+b.m,left:b.u,right:b.u+b.o};return b}):this.I.V==this.W.IE&&/^[11|12]/.test(this.I.va)?this.ma=function(b){var c=this.window.screenLeft-window.screenX,a=this.window.screenTop-window.screenY-this.P.Explorer.Y,c={left:c,top:a,right:c+this.window.innerWidth,bottom:a+this.window.innerHeight},
a={u:null,s:null,G:null,H:null,B:null,C:null,o:null,m:null,g:!1,rect:null,N:null,qa:null};a.u=c.left;a.s=c.top;a.G=null;a.H=null;a.B=b.D+c.left;a.C=b.F+c.top;a.o=this.window.innerWidth;a.m=this.window.innerHeight;a.g=!0;a.rect=c;this.b.Ab()&&(a=this.ib(a));return a}:this.I.V==this.W.IE&&/[6-9]|[10]/.test(this.I.va)?this.ma=function(){if(8==document.documentMode)return{u:null,s:null,G:null,H:null,B:null,C:null,o:null,m:null,g:!1,rect:null,N:null,qa:null};var b=this.window.Qa&&this.window.sa?this.window.Qa.Mb-
this.window.sa.Mb:0,c=this.window.Qa&&this.window.sa?this.window.Qa.Lb-this.window.sa.Lb:0,a=this.b.Sa(this.window),d={u:null,s:null,G:null,H:null,B:null,C:null,o:null,m:null,g:!1,rect:null,N:null,qa:null};d.u=c;d.s=b;d.G=null;d.H=null;d.B=this.window.sa?c+this.window.sa.Ea:null;d.C=this.window.sa?b+this.window.sa.Fa:null;d.o=this.window.innerWidth||a.clientWidth;d.m=this.window.innerHeight||a.clientHeight;d.g=!0;d.rect={left:c,top:b,right:c+(this.window.innerWidth||a.clientWidth),bottom:b+(this.window.innerHeight||
a.clientHeight)};this.b.Ab()&&(d=this.ib(d));return d}:this.b.qb()?(p=512,this.ma=function(){var b={u:null,s:null,G:null,H:null,B:null,C:null,o:null,m:null,g:!1,rect:null,N:null,qa:null};null!=this.f&&(adData=this.b.kb(this.f),b.o=adData?adData.w:this.window.innerWidth,b.m=adData?adData.h:this.window.innerHeight);return b}):this.ma=this.I.V==this.W.Chrome?function(){var b=null,c=null,a=!1;try{var d=this.window.frameElement.offsetTop,b=this.window.frameElement.offsetLeft-this.window.frameElement.offsetParent.scrollLeft,
c=d-this.window.frameElement.offsetParent.scrollTop,a=!0}catch(m){}d={u:null,s:null,G:null,H:null,B:null,C:null,o:null,m:null,g:!1,rect:null,N:null,qa:null};d.u=b;d.s=c;d.G=null;d.H=null;d.B=null;d.C=null;d.o=this.window.innerWidth;d.m=this.window.innerHeight;d.g=a;d.rect=a?{left:b,top:c,right:b+this.window.innerWidth,bottom:c+this.window.innerHeight}:null;this.b.Ab()&&(d=this.ib(d));return d}:null!=this.fa&&this.fa.Ua()?function(){var b={u:null,s:null,G:null,H:null,B:null,C:null,o:null,m:null,g:!1,
rect:null,N:null,qa:null};null!=this.f&&(adData=this.b.kb(this.f),b.o=adData?adData.w:this.window.innerWidth,b.m=adData?adData.h:this.window.innerHeight);return b}:function(){return{u:null,s:null,G:null,H:null,B:null,C:null,o:null,m:null,g:!1,rect:null,N:null,qa:null}}:this.ma=function(b){var c=this.$b(this.f,this.window),a={u:null,s:null,G:null,H:null,B:null,C:null,o:null,m:null,g:!1,rect:null,N:null,qa:null},d=this.b.bc(this.f,this.window),m=this.b.xc(this.f,this.window);a.u=m.left;a.s=m.top;a.G=
c.x;a.H=c.y;a.B=b.D+m.left;a.C=b.F+m.top;a.o=m.w;a.m=m.h;a.g=!0;a.rect=d;a.N=m;return a};return this.ma(b,c)};this.ib=function(b){if(this.window.document.body==this.f||this.window.document.documentElement==this.f)return b;var c=this.b.kb(this.f);if(c){var l=c.w,f=c.h,a=b.u,d=b.s,m=b.C,e=b.B;null!=b.u&&null!=b.s&&null!=b.m&&null!=b.o&&b.rect&&(0<c.t?(d=b.s+c.t,null!=b.C&&(m=b.C+c.t)):f+=c.t,0<c.l?(a+=c.l,null!=b.B&&(e=b.B+c.l)):l+=c.l,c.r>b.o&&(l-=c.r-b.o),c.Dc>b.m&&(f-=c.Dc-b.m),b.o=0<l?l:0,b.m=0<
f?f:0,b.u=a,b.s=d,b.C=m,b.B=e,b.rect.left=b.u,b.rect.top=b.s,b.rect.right=b.u+c.w,b.rect.bottom=b.s+c.h,b.N={w:l,h:f,left:a,right:a+l,top:d,bottom:d+f})}return b};this.te=function(){var b=screen.availLeft||0;return{g:$dv.CommonData&&$dv.CommonData.deviceType&&1==$dv.CommonData.deviceType?"undefined"!==typeof b:!1,ub:screen.availWidth||screen.width,tb:screen.availHeight||screen.height,Hf:b,If:screen.availTop||0}};this.ge=function(){var b=this.te(),c=this.oa(b),l=this.ma(c,b);return{da:c,j:l,Za:b,Bb:(null==
c.D||null==c.F?0:this.ia.Ld)|(null==c.A||null==c.v?0:this.ia.Md)|(null==l.u||null==l.s?0:this.ia.Fd)|(null==l.G||null==l.H?0:this.ia.Hb)|(null==l.B||null==l.C?0:this.ia.Ed)|(null==l.m||null==l.o?0:this.ia.Ib)|(null==b.tb||null==b.ub?0:this.ia.Kd),K:this.Ic(l.m,l.o)}};this.Ic=function(b,c){null==b&&(b=0);null==c&&(c=0);return 242500<=b*c?!0:!1};this.oe=function(){this.b.a("c10");if(null!=this.f)if(this.b.Zc(this.f,this.window))try{var b={timeStamp:new Date,i:-3,ja:-3,L:null,K:!1,ea:0};if(!this.ec())return b;
var c=this.ge();if(!c.j.g||!c.da.g){if(this.b.wa(this.window)&&this.window.$sf.ext.inViewPercentage){var l=this.window.$sf.ext.inViewPercentage();return{timeStamp:new Date,i:l,ja:l,L:c,K:c.K,ea:16}}if(this.b.qb()&&this.ob)return l=0,null!=this.nb&&(l=Math.round(100*this.nb.intersectionRatio)),{timeStamp:new Date,i:l,ja:l,L:c,K:this.Ic(c.j.m,c.j.o),ea:512};if(this.fa.Ua()){var f={timeStamp:new Date,i:-3,ja:-3,L:null,K:!1,ea:2};if(0==this.fa.Le())f.i=-6,f.ja=-6,this.fa.pd(this.window,this.f);else{var a=
this.fa.ye();null!=a&&(f.L=c,f.K=c.K,f.i=a,f.ja=a)}return f}b.L=c;p&&(b.ea=p);return b}if(c.j&&c.j.N&&(0===c.j.N.w||1===c.j.N.w||0===c.j.N.h||1===c.j.N.h))return{timeStamp:new Date,i:-5,ja:-5,L:c,ea:p};l=c.j.N?this.ac(c.j.N,c.da,c.j.rect):this.ac(c.j.rect,c.da);return{timeStamp:new Date,i:l,ja:l,L:c,K:c.K,ea:p}}catch(d){return{timeStamp:new Date,i:-4,ja:-4,L:null,K:!1,ea:p}}else return{timeStamp:new Date,i:-2,ja:-2,L:null,K:!1,ea:0};else return{timeStamp:new Date,i:-1,ja:-1,L:null,K:!1,ea:0}};this.he=
function(b,c){this.b.a("c11");var f=null,g=null;if(null!=b.L){var a=b.L.j;c<=this.P.Ue&&(f=0<=b.i||-5==b.i?b.K&&b.i>=this.P.Wa||0==b.K&&50<=b.i?!0:!1:null,g=b.K?this.P.Wa/100:.5,g=0==f?0>a.s+a.m*g?!0:!1:1==f?!1:null)}return{Xc:g,Yc:f}};this.pb=function(b){this.b.a("c12");var c=null;if(2!=b.ea&&512!=b.ea&&null!=b.L){var f=b.L.Bb,g=b.L.j;(f&this.ia.Hb)==this.ia.Hb&&(f&this.ia.Ib)==this.ia.Ib&&(c=this.ac({left:g.G,top:g.H,right:g.G+g.o,bottom:g.H+g.m},b.L.da,g.rect),c=0<=b.i?b.K&&c>=this.P.Wa||0==b.K&&
50<=c?!1:!0:null)}this.b.a("c12e");return c};this.gd=function(){function b(f){f.forEach(function(b){c.nb=b})}var c=this;"undefined"!=typeof IntersectionObserver&&null!=this.f&&(p=512,this.sb=new IntersectionObserver(b,{threshold:[0,.1,.2,.3,.4,.5,.6,.7,.8,.9,1]}),this.sb.observe(this.f),this.ob=!0)};this.Fe=function(){this.f=null;null!=this.sb&&(this.sb.disconnect(),this.nb=null,this.ob=!1)}}
function H(){this.getElementVolume_object=function(b){var g=b.getAttribute("width"),c=b.getAttribute("height");null==g||""==g||null==c||""==c?(b=b.parentNode,b={w:b.clientWidth,h:b.clientHeight}):b={w:g,h:c};return b};this.Me=function(b){var g=0;try{for(;null!=b&&10>g;){if("none"==window.getComputedStyle(b).display||"hidden"==window.getComputedStyle(b).visibility)return!1;b=b.parentElement;g++}}catch(c){}return!0};this.na=function(b,g){this.a("cm1");var c=null,f=b.nodeName.toLowerCase();g&&this["getElementVolume_"+
f]&&(c=this["getElementVolume_"+f](b));if(!c&&(c=this.kb(b),this.a("cm2e"),!c||1>=c.w||1>=c.h))return this.a("cm1e"),{w:0,h:0};c.w.indexOf&&c.w.indexOf("px")&&(c.w=c.w.replace("px",""));c.h.indexOf&&c.h.indexOf("px")&&(c.h=c.h.replace("px",""));this.a("cm1e");return c};this.kb=function(b){this.a("cm2");try{var g;return document.body.getBoundingClientRect&&(g=b.getBoundingClientRect())?{w:g.right-g.left,h:g.bottom-g.top,l:g.left,t:g.top,Dc:g.bottom,r:g.right}:null}catch(c){return null}};this.Sa=function(b){this.a("ff8");
b=b.document.documentElement.clientHeight?b.document.documentElement:b.document.body;this.a("ff8e");return b};this.Pc=function(b,g){this.a("ff9");var c=0,f=!1;if(b.document.all)for(var q=0;q<b.document.all.length;q++)"BODY"==b.document.all[q].nodeName&&(f=!0),f&&("width"==g?b.document.all[q].width>c&&(c=b.document.all[q].width):b.document.all[q].height>c&&(c=b.document.all[q].height));this.a("ff9e");return c};this.cd=function(b,g){for(var c=this.Sa(b),f=b.innerWidth||c.clientWidth||this.Pc(b,"width"),
c=b.innerHeight||c.clientHeight||this.Pc(b,"height"),q=g.length,h=0,k=0;k<q;k++)if(15>=Math.abs(f-g[k].w)){h=g[k].h.length;for(f=0;f<h;f++)if(15>=Math.abs(c-g[k].h[f]))return!0;break}return!1};this.sf=function(b){for(var g=[],c=-1;g[++c]=b[c];);g.length--;return g};this.Eb=function(b,g,c,f){var q=b.getElementsByTagName("*"),q=this.sf(q);q.unshift(b);for(var h=["EMBED","IFRAME","OBJECT","IMG","DIV"],k=[],p=0;p<q.length;p++){var u=q[p];if(-1!=h.indexOf(u.nodeName)){var r=f(u);r&&k.push({Cc:r.w*r.h,
w:r.w,h:r.h,type:u.nodeName||"other",ce:u})}}k=k.sort(function(b,c){return c.Cc-b.Cc||h.indexOf(c.type)-h.indexOf(b.type)});(g=0<k.length&&k[0].w>g&&k[0].h>c?k[0].ce:null)&&b&&(g.fc=b.fc);return g};this.Zc=function(b,g){this.a("ff10");try{if(!b)return!1;for(g||(g=window);b!=g.document&&b.parentNode;)b=b.parentNode;this.a("ff10e");return b==g.document}catch(c){return!1}};this.bc=function(b,g){var c=g.parent,f={left:0,right:0,top:0,bottom:0};if(b){var h=b.getBoundingClientRect();g!=c&&this.Jb(g,c)&&
(f=this.bc(g.frameElement,c));f={left:h.left+f.left,right:h.right+f.left,top:h.top+f.top,bottom:h.bottom+f.top}}return f};this.Jb=function(b,g){var c=!1;if(b==g)c=!0;else try{b.document.domain==g.document.domain&&(c=!0)}catch(f){}return c};this.Wc=[];this.pe=function(b){if(b&&!this.$c(b,this.Wc))try{if(b.contentDocument&&b.contentDocument.getElementsByTagName)return b.contentDocument;if(b.contentWindow&&b.contentWindow.document&&b.contentWindow.document.getElementsByTagName)return b.contentWindow.document}catch(g){this.Wc.push(b)}return null};
this.Be=function(b){return b?b.defaultView||b.parentWindow:null};this.$c=function(b,g){return-1<g.indexOf(b)};var h=null;this.ie=function(b){if(h!=b)try{return b!=b.top&&b.parent&&b.parent.document?b.parent:null}catch(g){return h=b,null}else return null};this.xc=function(b,g){var c=g.parent,f={w:0,h:0,left:0,right:0,top:0,bottom:0};b&&(f=this.bc(b,g),f.w=f.right-f.left,f.h=f.bottom-f.top,g!=c&&this.Jb(g,c)&&(c=this.xc(g.frameElement,c),c.bottom<f.bottom&&(c.bottom<f.top&&(f.top=c.bottom),f.bottom=
c.bottom),c.right<f.right&&(c.right<f.left&&(f.left=c.right),f.right=c.right),f.w=f.right-f.left,f.h=f.bottom-f.top));return f};this.Tb=function(b,g){return function(){return b.apply(g,arguments)}};this.ta=function(b){try{return b?b.length?b.length:0:0}catch(g){return 0}};this.dc=function(b){for(var g=[],c=0;c<b.length;c++)this.Me(b[c])&&g.push(b[c]);return g};this.a=function(b){try{maxLength=3,$dv&&($dv.Ja=$dv.Ja||[],$dv.Ja.push(b),$dv.Ja.length>maxLength&&$dv.Ja.shift())}catch(g){}};this.mb=function(){try{return $dv&&
$dv.Ja?"&dvp_log="+$dv.Ja.join():""}catch(b){return""}};this.wa=function(b){if(b.$sf&&b.$sf.ext)if(b.$sf.ext.geom){if(b=b.$sf.ext.geom(),null!=b&&b.win&&(0<b.win.h||0<b.win.w))return this.wa=function(){return!0},!0}else if(b.$sf.ext.inViewPercentage)return!0;this.wa=function(){return!1};return!1};this.ic=function(b){return b.context&&b.context.observeIntersection?!0:!1};this.qb=function(){var b=!1;if(1==this.Ra("disableIO"))return!1;"undefined"!=typeof IntersectionObserver&&(b=!0);return b};this.rb=
function(b,g,c){var f=c&&c.Enums.BrowserId||window.$dv.Enums.BrowserId;if(b==(c&&c.Enums.TrafficScenario||window.$dv.Enums.TrafficScenario).CrossDomain&&g.V===f.Safari&&(null===g.va||void 0===g.va||!/^[3-8]/.test(g.va)))return this.rb=function(){return!0},!0;this.rb=function(){return!1};return!1};this.Ra=function(b){var g,c=this.Nc();c&&c.AVO&&(g=c.AVO[b]);return g};this.Nc=function(){var b={},g=window.$dv,c=window.$uid;g.tags&&g.tags[c]&&(b=g.tags[c]);return b};this.Ab=function(){return 1==this.Ra("sam")?
!0:!1};this.Ia=new function(){var b=this;b.cache=[];window.addEventListener?b.add=function(g,c,f,h,t){if("undefined"==typeof h||null==h)h=window;h.addEventListener(g,c,f);t&&b.cache.push([g,c,f,h])}:window.attachEvent?b.add=function(g,c,f,h,t){if("undefined"==typeof h||null==h)h=window;h["e"+g+c]=c;h[g+c]=function(){h["e"+g+c](window.event)};h.attachEvent("on"+g,h[g+c]);t&&b.cache.push([g,c,f,h])}:b.add=function(){};window.removeEventListener?b.remove=function(b,c,f,h){if("undefined"==typeof h||null==
h)h=window;h.removeEventListener(b,c,f)}:window.detachEvent?b.remove=function(b,c,f,h){if("undefined"==typeof h||null==h)h=window;h.detachEvent("on"+b,h[b+c]);h[b+c]=null;h["e"+b+c]=null}:b.remove=function(){};b.flush=function(){for(var g=0;g<b.cache.length;g++)b.remove.apply(b,b.cache[g]);b.cache=[]}}}
function ja(h,b,g,c,f){function q(a,d){for(var b=[],c=0;c<r.length;c++)for(var f=d(a,r[c]),l=k.Be(r[c]),g=0;g<k.ta(f);g++)f[g].fc=l,b.push(f[g]);return b}function t(a,d,b,c){null!==a&&$dv&&h&&($uid||h.impressionId)&&$dv.registerEventCall(h.impressionId||$uid,{dvp_calinf:c+"-"+b,dvp_calerr:a.slice(0,500),dvp_calplc:d})}var k=new H,p="Microsoft Internet Explorer"==navigator.appName;this.c=c;this.window=g;this.Cb=[["DCF",'"'],[";",";"],["%3B","%3B"],["zoneid=","_"],["zoneid%3D","_"],["PRImpID=",""],
["PRImpID%3D",""],["PRPID=",""],["PRPID%3D",""]];this.nc=[1==p?"object":"embed",1==p?"embed":"object","href","img","span","iframe","frameElement","div"];this.yb=this.f=null;this.dataObj=h;this.dvObj=h.dvObj||window.$dv;this.I={V:this.dvObj.CommonData.BrowserId,va:this.dvObj.CommonData.BrowserVersion};this.W=this.dvObj.Enums.BrowserId;this.M=f;this.X=this.dvObj.Enums.TrafficScenario;this.Yd=function(){var a=this.dataObj.Vb+"-"+this.dataObj.Sb;this.dataObj.isBrandShieldOrigin&&(a+="-bs");return a.replace(RegExp(",",
"g"),";")};this.rc=this.Yd();this.S=b;this.O={R:{h:1,w:1},xf:{h:10,w:10},Se:10};115==this.dataObj.Ob&&(this.O.R.h=20,this.O.R.w=20);this.dataObj.findclass&&1==this.dataObj.findclass&&this.nc.push("classDeclaration");this.searchByAdSrvId_8=function(a,d){k.a("a1");var b=/[0-9]+-[0-9]+-[0-9]+-[0-9]+/.exec(a);return null!=b&&(b=b.toString(),b.replace(RegExp("-","g"),"")==d)?!0:!1};this.Wb=this["searchByAdSrvId_"+(this.dataObj?this.dataObj.Ob||"":"")];this.getElementsByClassName=function(a,d){return q(a,
function(a,b){k.a("ff1");var c=b.getElementsByClassName(a);k.a("ff1e");return"1"!=d?c:k.dc(c)})};this.querySelectorAll=function(a,d){return q(a,function(a,b){k.a("ff3");var c=b.querySelectorAll("."+a);k.a("ff3e");return"1"!=d?c:k.dc(c)})};this.getElementsByTagName=function(a,d){return q(a,function(a,b){k.a("ff4");var c=b.getElementsByTagName(a);k.a("ff4e");return"1"!=d?c:k.dc(c)})};this.classDeclaration=function(){k.a("a9");var a="undefined"!==typeof window.document.getElementsByClassName,d="undefined"!==
typeof window.document.querySelectorAll;if(!(1>this.dataObj.J.length)){var b=[];if(a)b=this.getElementsByClassName(this.dataObj.J,this.dataObj.displaynon);else if(d)b=this.querySelectorAll(this.dataObj.J,this.dataObj.displaynon);else return;a=k.ta(b);for(d=0;d<a;d++)if(b[d]&&!this.pa(b[d])){this.aa(b[d]);this.f=b[d];break}}};this.div=function(){if(!(1>this.dataObj.J.length))for(var a=this.getElementsByTagName("div",this.dataObj.displaynon),d=k.ta(a),b=0;b<d;b++)if(a[b]&&this.ya(this.dataObj,a[b],
!0)&&!this.pa(a[b])){var c=k.na(a[b]);if(c&&c.h>this.O.R.h&&c.w>this.O.R.w){this.f=a[b];this.aa(a[b]);break}else if(this.f=k.Eb(a[b],this.O.R.w,this.O.R.h,k.Tb(k.na,k))){this.aa(this.f);this.aa(a[b]);break}}};this.span=function(){k.a("a10");if(!(1>this.dataObj.J.length))for(var a=this.getElementsByTagName("span",this.dataObj.displaynon),d=k.ta(a),b=0;b<d;b++)if(a[b]&&this.ya(this.dataObj,a[b],!0)&&!this.pa(a[b])){if(this.He(a[b])){this.f=a[b];break}if(this.f=k.Eb(a[b],this.O.R.w,this.O.R.h,k.Tb(k.na,
k))){this.aa(this.f);this.aa(a[b]);break}}};this.object=function(){k.a("a11");for(var a=this.getElementsByTagName("object",this.dataObj.displaynon),b=k.ta(a),c=0;c<b;c++)if(a[c]&&this.ya(this.dataObj,a[c])&&!this.pa(a[c])&&(this.f=k.Eb(a[c],this.O.R.w,this.O.R.h,k.Tb(k.na,k)))){this.aa(this.f);this.aa(a[c]);break}};this.embed=function(){k.a("a12");for(var a=this.getElementsByTagName("embed",this.dataObj.displaynon),b=k.ta(a),c=0;c<b;c++)if(a[c]&&this.ya(this.dataObj,a[c])&&!this.pa(a[c])){var e=k.na(a[c]);
if(e&&e.h>this.O.R.h&&e.w>this.O.R.w){this.f=a[c];this.aa(a[c]);break}}};this.href=function(){k.a("a13");for(var a=this.getElementsByTagName("a",this.dataObj.displaynon),b=k.ta(a),c=0;c<b;c++)if(a[c]&&this.ya(this.dataObj,a[c])&&!this.pa(a[c])){var e=a[c].getElementsByTagName("img");if(0<e.length){var f=k.na(e[0]);if(f&&f.h>this.O.R.h&&f.w>this.O.R.w){this.f=e[0];this.aa(a[c]);break}}}};this.img=function(){k.a("a14");for(var a=this.getElementsByTagName("img",this.dataObj.displaynon),b=k.ta(a),c=0;c<
b;c++)if(a[c]&&this.ya(this.dataObj,a[c])&&0>a[c].src.indexOf("event")&&!this.pa(a[c])){var e=k.na(a[c]);if(e&&e.h>this.O.R.h&&e.w>this.O.R.w){this.f=a[c];this.aa(a[c]);break}}};this.iframe=function(){k.a("a15");for(var a=this.getElementsByTagName("iframe",this.dataObj.displaynon),b=k.ta(a),c=0;c<b&&!this.Ac(a[c]);c++);};this.frameElement=function(){k.a("a16");this.M==this.X.SameDomain&&this.Ac(this.window.frameElement)};this.Ac=function(a){k.a("a17");return this.ya(this.dataObj,a)?this.Nd(a):!1};
this.aa=function(a){k.a("a18");if(a&&0==this.pa(a)){var b=a.getAttribute("dvvisit");b?a.setAttribute("dvvisit",b+","+this.rc):(k.a("ff5"),b=this.window.document.createAttribute("dvvisit"),k.a("ff5e"),b.value=this.rc,a.setAttributeNode(b))}};this.Xe=function(a){a&&a.hasAttribute&&a.hasAttribute("dvvisit")&&a.removeAttribute("dvvisit")};this.bf=function(){this.Xe(this.f);this.f=null};this.pa=function(a){k.a("a19");if(a&&(a=a.getAttribute("dvvisit"))){a=a.split(",");for(var b=0;b<a.length;b++)if(a[b]==
this.rc)return!0}return!1};this.He=function(a){k.a("a20");return a&&"1"==a.getAttribute("adunit")?!0:!1};this.Nd=function(a){k.a("a21");if(a&&!this.pa(a)){var b=k.na(a);if(b&&b.h>this.O.R.h&&b.w>this.O.R.w)return this.f=a,this.aa(a),!0}return!1};this.ya=function(a,b,c){k.a("a22");var e=null;return a.J&&0<a.J.length&&(this.yc=1==a.Ne?this.Bd:this.Fb,e=this.Hd(a,b,c))||!this.f&&(e=this.Id(a,b))?!0:!1};this.Hd=function(a,b,c){k.a("a23");var e;try{if(a.Hc&&b&&b.hasAttribute&&b.hasAttribute("dv-view"))return!0;
(e=this.za(b.id,a.J))||(e=this.za(b.src,a.J));e||(e=this.za(b.href,a.J));e||(e=this.za(b.getAttribute("flashvars"),a.J));e||(e=this.za(b.name,a.J));e||c||(e=this.za(b.innerHTML,a.J));e&&!c&&(e=this.Gd(a,b),a.J!=a.Aa&&(u.dvp_btaddv=1),0==e?u.dvp_btadcf+=1:u.dvp_btadsf=1);return e}catch(f){return e}};this.Id=function(a,b){k.a("a24");var c;try{if(a.Hc&&b&&b.hasAttribute&&b.hasAttribute("dv-view"))return!0;(c=this.Da(b.id,a))||(c=this.Da(b.src,a));c||(c=this.Da(b.href,a));c||(c=this.Da(b.Cf,a));c||(c=
this.Da(b.name,a));c||(c=this.Da(b.innerHTML,a));return c}catch(e){return c}};this.Da=function(a,b){k.a("a25");if(!a)return!1;a=a.toLowerCase();for(var c=0;c<this.Cb.length;c++){var e;if(b.Bc&&(e=(this.Cb[c][0]+b.Bc).toLowerCase(),e=a.indexOf(e),-1<e)||b.ed&&(e=(this.Cb[c][0]+b.ed).toLowerCase(),e=a.indexOf(e),-1<e))return!0}return!1};this.Gd=function(a,b){k.a("a26");return null==a.Aa||""==a.Aa?!1:this.za(this.Ad(b),a.Aa)};this.Ad=function(a){k.a("a27");if(a.outerHTML)return a.outerHTML;for(var b=
a.attributes.length,c="",e=0;e<b;e++)c=c+a.attributes[e].nodeName+"="+a.attributes[e].nodeValue+" ";return c+a.innerHTML};this.za=function(a,b){k.a("a28");return!a||!b||5>b.length?!1:null!=(this.yc?this.yc(a,b):this.Fb(a,b))?!0:this.Wb&&"function"===typeof this.Wb?this.Wb(a,b):!1};this.Bd=function(a,b){k.a("a29");var c;try{c=(new RegExp(b)).exec(a)}catch(e){c=this.Fb(a,b)}return c};this.Fb=function(a,b){k.a("a30");var c=null;-1!==a.indexOf(b)&&(c=a);return c};var u={dvp_btreg:h.J,dvp_btadsrv:h.Aa,
dvp_btaddv:0,dvp_btadcf:0,dvp_btadsf:0};btsvrreg_sent=!1;this.ee=function(a){k.a("a31");u.dvp_btaddv=0;u.dvp_btadcf=0;u.dvp_btadsf=0;if(this.re())return this.c.vd(),!btsvrreg_sent&&$dv&&window.$uid&&(a=h&&h.impressionId||window.$uid,$dv.registerEventCall(a,u),btsvrreg_sent=!0),this.hc||(this.hc=!0),this.f;if(this.dataObj.J&&0<this.dataObj.J.length&&!0===this.hc&&1<a)return this.f;"1"!=this.dataObj.displaynon&&(a=this.se(),a.node&&(this.c.ud(a.Ha),this.f=a.node,!btsvrreg_sent&&$dv&&window.$uid&&(h.J||
h.Aa)&&(a=h&&h.impressionId||window.$uid,$dv.registerEventCall(a,u),btsvrreg_sent=!0)));return this.f};var r;this.re=function(){k.a("32");if(this.dataObj.J&&0<this.dataObj.J.length){var a=this.nc.length,b=this.window,c=0,e=[],f=null,g=null;do{try{var l=b.document}catch(h){f=h.message;g="0";t(f,g,e.length,c);break}try{l&&l.getElementsByTagName&&e.push(l)}catch(h){f=h.message;g="1";t(f,g,e.length,c);break}try{if(f=e,l)for(var n=l.getElementsByTagName("iframe"),g=0;g<n.length;g++){var q=k.pe(n[g]);void 0!==
q&&null!==q&&0==k.$c(q,f)&&f.push(q)}}catch(h){f=h.message;g="2";t(f,g,e.length,c);break}try{b=k.ie(b)}catch(h){f=h.message;g="3";t(f,g,e.length,c);break}}while(b&&10>++c);r=e;for(b=0;b<a;b++)if(this[this.nc[b]](),this.f){this.yb=this.f;break}}return this.f};var l=[],n=["object","embed","img","iframe"];this.dataObj.spotXmode&&(n=["object","embed","video","iframe"]);this.Je=function(a){k.a("a33");a=k.na(a);return this.Ke(a)};this.Ke=function(a){if(a){var d=a.w;a=a.h;for(var c=b.length,e=0,f=0;f<c;f++)if(15>=
Math.abs(d-b[f].w))for(var e=b[f].h.length,g=0;g<e;g++)if(15>=Math.abs(a-b[f].h[g]))return!0}return!1};this.le=function(){k.a("a34");return this.dataObj.isBrandShieldOrigin?this.me():this.ne()};this.ne=function(){k.a("a35");var a=(window.name||(window.frameElement?window.frameElement.id:"")).substr(7),b=window.parent;k.a("ff6");b=b.document.getElementsByTagName("script");k.a("ff6e");for(var c=b.length,e=0;e<c;e++)if(b[e]&&b[e].id&&b[e].id.substr(7)==a)return b[e];return null};this.me=function(){k.a("a36");
return this.dvObj.tags[this.dataObj.impressionId].tagElement};this.se=function(){k.a("a37");var a=this.le();return this.Sd(a)};this.Sd=function(a){k.a("a38");var b={node:a,Ha:0};a=[];for(l=[];b||0<a.length;){try{var c;a:{var e=b.node;try{if(e&&-1!=n.indexOf(e.nodeName.toLowerCase())){c=!0;break a}}catch(f){}c=!1}if(c&&this.Je(b.node)&&!this.pa(b.node))return this.aa(b.node),b;if(b.Ha<=this.O.Se){var g,h=b.node,r=b.Ha,b=[],q=h.parentNode;q&&-1==l.indexOf(q)&&(l.push(q),b.push({node:q,Ha:r+1}));if(h.hasChildNodes())for(var p=
0;p<h.childNodes.length;p++)h.childNodes[p]&&-1==l.indexOf(h.childNodes[p])&&1===h.childNodes[p].nodeType&&(l.push(h.childNodes[p]),b.push({node:h.childNodes[p],Ha:r+1}));var t,u=h,U=[],y=null;u&&u.parentNode&&(y=u.parentNode.firstChild);for(;y;)1===y.nodeType&&y!==u&&U.push(y),y=y.nextElementSibling||y.nextSibling;t=U;for(p=0;p<t.length;p++)t[p]&&-1==l.indexOf(t[p])&&1===t[p].nodeType&&(l.push(t[p]),b.push({node:t[p],Ha:r+1}));if(g=b)for(b=0;b<g.length;b++)a.push(g[b])}}catch(f){}b=a.shift()}return{node:null}};
return this}
function dv_CustomClientViewAssureService(h){function b(b){return{settings:b.settings,buckets:0,reported:!1,eventId:b.eventId,La:b.La,gb:b.gb}}this.dvObj=h.dvObj||window.$dv;this.impressionId=h.impressionId||window.$uid;this.b=new H;var g=[],c=null,f=null,q=null,t=null;this.dvObj&&this.dvObj.tags&&this.dvObj.tags[this.impressionId]&&(c=this.dvObj.tags[this.impressionId].cvmSettings,f=this.dvObj.tags[this.impressionId].billable,q=this.dvObj.tags[this.impressionId].bprjct,t=this.dvObj.tags[this.impressionId].gmmod);this.vc=
window.dv_cvmSettings||c||h.cvmSettings;this.Pb=window.dv_billable||f||h.billable;this.Gc=window.Ff||q||h.bprjct;this.Tc=window.Gf||t;this.Zd=new b({settings:this.vc,eventId:6,La:["CustomViewabilityViewable"]});var k=this.b.Ra("rpv"),c=this.b.Nc().bgm;h.Va=1==k&&1==c;this.Fc=new b({settings:this.Pb,eventId:17,La:h.Va?["BillableViewedImpression"]:["BillableViewedImpression","GroupMPassedImpression"],gb:!0});this.vc&&g.push(this.Zd);this.Pb&&g.push(this.Fc);h.la=h.la||[];c={serverProperties:{projected:"bp",
viewed:"bpv",viewedRate:"bpvr",error:"bperr"},reportQueryString:{projected:"isbprjct",measurems:"isbmms",viewedms:"isbvms",viewrate:"prjctbvr",error:"prjctber"}};this.Gc&&(c={serverData:this.Gc,projectionData:c,reportRTN:!0},h.la.push(c));c={serverProperties:{projected:"gmp",viewed:"gmpv",viewedRate:"gmpvr",error:"gmperr"},reportQueryString:{projected:"isgmmod",measurems:"isgmmims",viewedms:"isgmpims",viewrate:"modgmvr",error:"modgmer"}};this.Tc&&(c={serverData:this.Tc,projectionData:c,reportRTN:!0},
h.la.push(c));this.Rd=dv_InViewService;this.Rd(h);var p=this.Gb;this.Gb=function(b){b=p(b);for(var c=0;c<g.length;c++){var f=this.ze(b,g[c]);this.tf(f,g[c]);this.Pd(g[c])}return b};var u=this.Ma;this.Ma=function(b,c){u(b,c);this.Pb&&1==this.Xb&&(this.xa(["BillableMeasuredImpression"]),k?0==this.dataObj.Va&&this.xa(["GroupMMeasuredImpression"]):1!=this.dataObj.irtf&&this.xa(["GroupMMeasuredImpression"]))};this.ze=function(b,c){"undefined"===typeof c.settings.focus||c.settings.focus||(b.i=b.ja);return b};
this.tf=function(b,c){(!c.settings.measureType||"consecutive"==String(c.settings.measureType).toLowerCase())&&b.i<c.settings.adArea?c.buckets=0:b.i>=c.settings.adArea&&(!c.gb||1!=this.dataObj.irtf)&&(c.buckets+=this.ba.interval);c.K=b.K};this.Pd=function(b){b.af||b.gb&&1==this.dataObj.irtf||!(this.Jd(b)||b===this.Fc&&b.settings&&!b.settings.doNotReportViewedOnLargeAd&&b.K)||(this.U.$(this.c.ca(b.eventId),b.eventId),b.La&&this.xa(b.La),b.af=!0)};this.Jd=function(b){return b.buckets>=b.settings.duration?
!0:!1}}
function dv_InViewService(h){function b(){null===f.interval&&(f.interval=setInterval(f.qe(),f.ba.interval))}function g(){if(!1===f.bd){f.bd=!0;try{f.b.Ia.remove("load",arguments.callee,!1,element)}catch(a){}f.Pa=new ja(f.dataObj,f.S,f.window,f.c,f.M);f.vb();f.b.a("s41");f.ua=new ia(f.Ud?f.Ud:f.window,f.f,f.M,f.I,f.P,f.c.Rb,f.dvObj,f.impressionId);f.b.a("s42");f.start();f.Dd()}}function c(a,b){f.b.Ia.add("click",function(){f.Kb(!0);$dv.registerEventCall(f.impressionId,"ad"==b?{dvp_csad:1}:{dvp_csifr:1});f.b.Ia.remove("click",
arguments.callee,!1,a)},!1,a,!1)}var f=this;this.dd=10;this.Nb=h.serverSettings&&h.serverSettings.jsVersion?h.serverSettings.jsVersion:"611";this.dvObj=h.dvObj||window.$dv;this.impressionId=h.impressionId||window.$uid;this._minor_version="0";this.b=new H;this.Ae=function(){for(var a=document.getElementsByTagName("script"),b=a.length,c,e=0;e<b;e++)if(c=a[e].src,/visit[.]js/.test(c))return c.substring(c.indexOf("?")+1)};this.bd=!1;var q={serverProperties:{projected:"p",error:"perr",viewed:"pv",featurebit:"fb",
viewedRate:"pvr"},reportQueryString:{projected:"isprjct",measurems:"ismms",viewedms:"isiabvms",viewrate:"prjctvr",error:"prjcter"}},t=!1,k=!1;this.la=h.la||[];(this.uf=h.prjct)&&this.la.push({serverData:h.prjct,projectionData:q,Ze:!0,vf:["MeasurementCapabilityDetected","ProjectedMeasured","IabView","ProjectedAssignedViewed"],Te:["MeasurementCapabilityDetected","ProjectedMeasured"]});q={serverProperties:{projected:"up",error:"uperr",viewed:"upv",viewedRate:"upvr"},reportQueryString:{projected:"isuprjct",
measurems:"isumms",viewedms:"isuiabvms",viewrate:"uprjctvr",error:"uprjcter"}};this.dvObj&&this.dvObj.tags&&this.dvObj.tags[this.impressionId]&&this.dvObj.tags[this.impressionId].uprjct&&this.la.push({serverData:this.dvObj.tags[this.impressionId].uprjct,projectionData:q});this.ve=function(){var a="";this.dvObj&&this.dvObj.tags&&this.dvObj.tags[this.impressionId]&&this.dvObj.tags[this.impressionId].tagElement&&(a=this.dvObj.tags[this.impressionId].tagElement.src,a=a.substring(a.indexOf("?")+1));return a};
this.Sc=function(){return((new Date).getTime()+""+Math.floor(1E6*Math.random())).substr(0,16)};this.ha=function(a,b){a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");var c=(new RegExp("[\\?&]"+a+"=([^&#]*)")).exec("?"+b);return c=c?c[1]:null};this.xe=function(){var a=this.ha("uid",this.T);null==a?(a=this.Sc(),this.T=this.T+"&uid="+a):""==a&&(a=this.Sc(),this.T=this.T.replace("&uid=","&uid="+a));return a};this.oc=function(a,b,c,e){if(e&&e.insertBefore&&e.firstChild&&(a=this.window.document.createElement(a))){for(var f in b)a[f]=
b[f];for(f in c)a.style[f]=c[f];e.insertBefore(a,e.firstChild);return a}return null};this.Td=function(){var a=this.dvObj.Enums.TrafficScenario;try{if(window.top==window)return a.OnPage;if(window.top.document.domain==window.document.domain)return a.SameDomain}catch(b){}return a.CrossDomain};this.M=this.dvObj.CommonData.Scenario||this.Td();this.I={V:this.dvObj.CommonData.BrowserId,va:this.dvObj.CommonData.BrowserVersion};this.W=this.dvObj.Enums.BrowserId;this.X=this.dvObj.Enums.TrafficScenario;this.Ya=
"default";this.dataObj=h;this.window=h.tagWindow||parent.window||window;this.yb=this.f=null;this.uc=this.Oa=!1;this.kc=!0;this.interval=null;this.T=this.Ae();this.xb=this.ve();this.We=h.serverSettings&&h.serverSettings.protocol&&0==h.serverSettings.protocol.indexOf("http")?h.serverSettings.protocol:window.location.protocol?window.location.protocol+"//":"http://";this.ba=window.be||this.window.be||{interval:100,Ba:{"default":{time:null,Ia:["beforeunload","unload"],qd:9E5}}};this.fd={};var q="tps300.doubleverify.com",
p=null;try{this.dvObj.tags[this.impressionId].ServerPublicDns&&(q=this.dvObj.tags[this.impressionId].ServerPublicDns)}catch(a){}this.ga=window.dv_configServer||this.window.dv_configServer||{protocol:this.We,port:"",domain:q,api:"event.jpg"};this.Z=window.ae||this.window.ae||{interval:1E3,ka:6};q=h&&h.sd?h.sd:!1;h=h&&h.td?h.td:!1;!1!==q&&!1!==h&&(this.Z.interval=q,this.Z.ka=h,$dv.registerEventCall(this.impressionId,{Af:this.Z.interval,Bf:this.Z.ka}));this.Xd={eb:12,Zb:10,Wa:30};this.P={Firefox:{Y:115},
Chrome:{Y:89},Safari:{Y:38},Explorer:{Y:55},Ue:500,Wa:30};var u=!1,r=0,l=[5,10,15];window.devicePixelRatio&&(this.P.Firefox.Y=0);this.dataObj.spotXmode=this.dataObj.videoEnable||this.dataObj.detectVideoPlayer||this.dataObj.spotXmode;this.dvObj&&this.dvObj.tags&&this.dvObj.tags[this.impressionId]&&this.dvObj.tags[this.impressionId].spotXmode&&(this.dataObj.spotXmode=this.dvObj.tags[this.impressionId].spotXmode);this.S=window.dv_configAdSize||this.window.dv_configAdSize||[{w:300,h:[100,250,268,600,
618,850,1050]},{w:160,h:[600,800]},{w:120,h:[60,90,240,600,800]},{w:970,h:[66,90,250,30,415,550]},{w:728,h:[90,120]},{w:88,h:[31]},{w:700,h:[500]},{w:250,h:[60,250,300]},{w:180,h:[150,160,600]},{w:234,h:[60]},{w:468,h:[60]},{w:550,h:[480]},{w:125,h:[125]},{w:336,h:[280,600,850]},{w:745,h:[90]},{w:954,h:[60]},{w:184,h:[90]},{w:800,h:[600]},{w:320,h:[360,50]},{w:1280,h:[100]},{w:640,h:[480,90]},{w:270,h:[460,202]},{w:613,h:[460]},{w:405,h:[303]},{w:950,h:[90]},{w:610,h:[100]},{w:272,h:[220]}];this.dataObj.spotXmode&&
(this.S.push({w:320,h:[240]}),this.S.push({w:400,h:[300]}),this.S.push({w:450,h:[338]}),this.S.push({w:600,h:[800]}),this.S.push({w:640,h:[360]}),this.S.push({w:854,h:[480]}),this.S.push({w:500,h:[375]}));$dv&&$dv.CommonData&&(2==$dv.CommonData.deviceType||3==$dv.CommonData.deviceType)&&(this.S.push({w:320,h:[480]}),this.S.push({w:300,h:[50]}),this.S.push({w:120,h:[20]}),this.S.push({w:168,h:[28]}),this.S.push({w:216,h:[36]}));this.Uc=this.xe();this.Yb=!1;this.Db=function(a,b){this.window.Kc||(this.window.Kc=
[]);this.window.Kc.push({caller:a,Ef:b})};this.startTime=(new Date).getTime();this.Od=4;this.zc=0;this.ec=!0;this.logEvents={startMeasure:1,nonMeasurable:2,timeout:3,beforeunload:4,iabViewable:5,iabCustom:6,updateRTN:7,unload:8,projection:9,fraudMeasured:10,errorlevel1:16,yf:17,interval:32};this.Xb=!1;this.rd=function(){this.b.a("ie16");if(this.window.dv_logObject){var a=this.c.je();this.window.dv_logObject[this.Uc]=a}this.b.a("ie16e")};this.zb=function(a){this.b.a("ie17");this.zb=this.Yb?function(a){this.c.ld(a);
this.rd()}:function(a){this.c.ld(a)};this.zb(a)};this.tc=function(a,b){this.tc=this.Yb?function(a,b){this.c.kd(a,b);this.rd()}:function(a,b){this.c.kd(a,b)};this.tc(a,b)};this.vb=function(){this.b.a("s4");this.f=this.Pa.ee(this.Z.ka);this.yb=this.Pa.yb;!this.f&&this.M==this.X.CrossDomain&&this.b.wa(this.window)&&(this.Z.ka=0);this.f?(this.df(),this.c.Ye(this.f),t||(c(this.f,"ad"),t=!0),k||this.M!=this.X.CrossDomain&&this.M!=this.X.SameDomain||(c(window.parent,"ifr"),k=!0),setTimeout(b,this.Pa.hc?
10:50)):0<this.Z.ka?(this.Z.ka--,this.ef(),setTimeout(this.fe(),this.Z.interval)):(this.M==this.X.CrossDomain&&(this.b.cd(this.window,this.S)||this.b.wa(this.window))?(this.f=this.b.Sa(this.window),this.c.jd()):this.M==this.X.SameDomain&&this.b.cd(this.window,this.S)?(this.f=this.b.Sa(window.parent),this.c.jd(),this.Wd()):this.Z.ka=-1,setTimeout(b,10));this.b.a("s4e")};this.Wd=function(){for(var a=this.window;a.parent!=a.top;)a=a.parent;this.b.a("ff26");for(var b=a.parent.document.getElementsByTagName("iframe"),
c=b.length,e=0;e<c;e++)b[e].contentWindow==a&&(this.f=b[e],this.window=a.parent);this.b.a("ff26e")};this.ef=function(){this.dataObj.J&&this.dataObj.Aa?this.c.jf():this.c.kf()};this.df=function(){this.b.a("s9");this.Oa=!0;this.c.ff();this.b.a("s9e")};this.Qd=function(){this.dataObj.Ob=this.ha("adsrv",this.T)||"";this.dataObj.J=this.ha("btreg",this.T)||"";this.dataObj.ed=this.ha("plcid",this.T)||"";"8"==this.dataObj.Ob&&""==this.dataObj.btreg&&(this.dataObj.J=this.dataObj.plcid);this.dataObj.Aa=this.ha("btadsrv",
this.T)||"";this.dataObj.Bc=this.ha("adid",this.T)||"";this.dataObj.Ne=this.ha("isbtregex",this.xb)||"";this.dataObj.Vb=this.ha("ctx",this.T)||"";this.dataObj.Sb=this.ha("cmp",this.T)||"";this.dataObj.findclass=this.ha("findclass",this.xb)||"";this.dataObj.displaynon=this.ha("displaynon",this.xb)||"";this.dataObj.Hc=this.ha("bsdvview",this.xb)||""};this.Xa=function(a){a=this.xa(a);return 0<a.length?"&tagServiceResult="+encodeURIComponent(a.join(",")):""};this.xa=function(a){if(!this.dvObj||!this.impressionId)return[];
for(var b=[],c=0;c<a.length;c++){var e=this.dvObj.pubSub.publish(a[c],this.impressionId)||null;null!=e&&b.push(e)}return b};this.Ee=function(a){1==a&&(this.c.rf(),this.dvObj&&this.impressionId&&this.c.jc()&&(a=this.Xa(["MeasurementCapabilityDetected","GeoMeasured"]),this.U.$(this.c.ca(this.logEvents.fraudMeasured)+a,this.logEvents.fraudMeasured)))};this.De=function(a){var b="",c=a.serverData,e=a.projectionData;1==c[e.serverProperties.featurebit]&&(b=1==c[e.serverProperties.viewed]?this.Xa(a.vf):this.Xa(a.Te));
return b};this.wd=function(){this.dataObj.serverSettings&&this.dataObj.serverSettings.TKH&&(this.T+="&TKH="+this.dataObj.serverSettings.TKH)};this.$d=function(){Array.prototype.indexOf=function(a){if(null==this)throw new TypeError;var b=Object(this),c=b.length>>>0;if(0===c)return-1;var e=0;1<arguments.length&&(e=Number(arguments[1]),e!=e?e=0:0!=e&&Infinity!=e&&-Infinity!=e&&(e=(0<e||-1)*Math.floor(Math.abs(e))));if(e>=c)return-1;for(e=0<=e?e:Math.max(c-Math.abs(e),0);e<c;e++)if(e in b&&b[e]===a)return e;
return-1}};this.inViewManager=function(){try{Array.prototype.indexOf||this.$d();var a=this.ga.protocol+this.ga.domain+this.ga.port+"/"+this.ga.api;this.wd();this.c=new aa(this.Nb,this.T,a,this.Xd,this.dataObj);var b=new ba(this.window,this.Uc);this.dataObj.isReportingDisabled?(X.prototype=b,this.U=new X):this.U=b;this.dataObj.isRTNsDisabled&&(this.xa=function(){return[]});this.Yb=this.window.dv_logObject?!0:!1;this.lf();if(!this.c.Rb()&&(this.Ce(),void 0!=this.dataObj.prjct&&1==this.dataObj.prjct.p&&
1==this.dataObj.prjct.fb))return;this.Ee(this.dataObj.irtf);this.Qd();this.Pa=new ja(this.dataObj,this.S,this.window,this.c,this.M);var c=window.parent;"589953"==this.dataObj.Vb&&"587351"==this.dataObj.Sb||"589953"==this.dataObj.Vb&&"616389"==this.dataObj.Sb||"polite"==this.dataObj.Df?(setTimeout(g,15E3),this.b.Ia.add("load",function(){setTimeout(g,1E3)},!1,c,!1)):g()}catch(f){var e=this;this.Na(function(){e.Db("inViewManager",f);e.c.pc("inViewManager: "+f.message);e.U.$(e.c.ca(e.logEvents.errorlevel1),
e.logEvents.errorlevel1)},"inViewManager",f)}};this.Ce=function(){for(var a="",b=0;b<this.la.length;b++){var c=this.la[b];this.c.pf(c.serverData,c.projectionData);!0===c.Ze&&(a+=this.De(c))}0<this.la.length&&this.U.$(this.c.ca(this.logEvents.projection)+a,this.logEvents.projection)};this.ab=function(a){this.b.a("ie20");-6!=a.i&&(-3==a.i||-5!=a.i&&0>a.i&&-1==this.Z.ka)&&(this.wc(),this.ab=function(){})};this.wc=function(){this.U.$(this.c.ca(this.logEvents.nonMeasurable),this.logEvents.nonMeasurable);
this.xa(["ImpressionNotMeasured"]);this.wc=function(){}};this.Ma=function(a,b){a.b.a("ie21");if(0<=b.i||-5==b.i&&-1>=a.Z.ka){if(a.dvObj&&a.impressionId&&0==a.c.jc()){a.b.a("ie23");var c=a.Xa(["MeasurementCapabilityDetected","GeoMeasured"]);a.b.a("ie24");var e=a.c.ca(a.logEvents.startMeasure);a.U.$(e+c,a.logEvents.startMeasure)}else a.U.$(a.c.ca(a.logEvents.startMeasure),a.logEvents.startMeasure);a.Xb=!0;a.Ma=function(){};a.ab=function(){}}a.b.a("ie22")};this.Kb=function(a){this.b.a("ie25");if(this.c.Oc()||
a&&!0===a)this.b.a("ie27"),this.dvObj&&this.impressionId&&0==this.c.jc()?(this.b.a("ie28"),a=this.Xa(["IabView","GeoViewed"]),this.b.a("ie29"),this.U.$(this.c.ca(this.logEvents.iabViewable)+a,this.logEvents.iabViewable)):this.U.$(this.c.ca(this.logEvents.iabViewable),this.logEvents.iabViewable),u=!0,this.Kb=function(){};this.b.a("ie26")};this.acumulateViewableTime=function(a){if(u&&this.c.Oc())for(r+=a,a=0;a<l.length;a++)null!=l[a]&&r>=1E3*l[a]&&(this.xa(["viewd"+l[a]+"sec"]),l[a]=null)};var n="hidden";
this.hasFocus=function(){vis=["hidden","webkitHidden","mozHidden","msHidden","oHidden"];for(hiddenProp in vis)if(vis[hiddenProp]in document){n=vis[hiddenProp];break}this.hasFocus=1==this.b.Ra("fcs")&&this.I.V==this.W.IE&&document.hasFocus?function(){var a=this.window.document.hasFocus();this.M==this.X.OnPage&&(a=a&&this.kc);return a}:1==this.b.Ra("fcs")&&this.M!=this.X.CrossDomain&&document.hasFocus?function(){var a=!0,a=this.window.top.document.hasFocus();document.hasFocus&&this.M==this.X.OnPage&&
(a=a&&this.kc);return a}:"undefined"!==typeof document[n]?function(){return!this.window.document[n]}:document.hasFocus&&this.M!=this.X.CrossDomain?function(){return this.window.top.document.hasFocus()}:function(){return!0};return this.hasFocus()};this.cc=function(a){var b=a.ua.oe();a.b.a("ie12");null==this.f||-3==b.i||a.hasFocus()||(b.i=0);a.b.a("ie13");return p=b};this.Gb=function(a){a.b.a("ie1");var b=a.f?a.f.fc||a.window:a.window;a.ua.f=a.f;a.ua.window=b;a.b.a("ie2");b=a.cc(a);!a.Oa||-1!=b.i&&
-2!=b.i||(a.hd(a),a.vb());a.b.a("ie3");-5==b.i&&(a.Z.ka--,a.c.md(),a.Ka||(a.Ka=function(b){b=a.ua.pb(b);a.c.$a(b)}));a.b.a("ie4");a.Ka&&0<b.i&&(a.Ka(b),a.Ka=null);a.b.a("ie5");if(a.Oa&&!a.uc){a.uc=!0;var c=a.ua.pb(b);a.c.$a(c)}-5==b.i&&(a.hd(a),a.vb(),b=a.cc(a),-5==b.i&&0<a.Z.ka&&a.c.cf());a.b.a("ie6");a.tc(b,a.ba.interval);a.b.a("ie7");a.zb(b);a.b.a("ie8");a.c.od(b.ea);a.ab(b);a.b.a("ie9");a.Ma(a,b);a.b.a("ie10");a.Kb();a.b.a("ie11");a.acumulateViewableTime(a.ba.interval);a.b.a("ie12");return b};
this.hd=function(a){a.Oa=!1;a.f=null;a.Pa.bf();a.ua.Fe()};this.qe=function(){this.b.a("s26");var a=this;return function(){try{a.Gb(a)}catch(b){a.Na(function(){a.zc<a.Od&&(a.zc++,a.Db("getIntervalCallback",b),a.c.pc("getIntervalCallback: "+b.message),a.U.$(a.c.ca(a.logEvents.errorlevel1),a.logEvents.errorlevel1))},"getIntervalCallback",b)}}};this.Rc=function(a){var b=this;return function(){b.Na(function(){b.I.V==b.W.IE?b.U.$(b.c.ca(b.logEvents[a]),b.logEvents[a]):b.U.sc(b.c.ca(b.logEvents[a]),b.logEvents[a])},
"getReportEventCallback")}};this.fe=function(){var a=this;return function(){a.Na(function(){a.vb();a.f||a.c.wb()},"getAdLocateCallback")}};this.Ta=function(){var a=this;return function(b){try{b||(b=a.window.event),a.kc="blur"==b.type||"focusout"==b.type?!1:!0}catch(c){try{b=callerName||"unknown caller";var f="";a.b?f=a.b.mb():this.b&&(f=this.b.mb());var e=this.ga.protocol+this.ga.domain+this.ga.port+"/"+this.ga.api+"?"+this.T+"&ctime="+(new Date).getTime()+"&evid="+this.logEvents.errorlevel1+"&jsver="+
this.Nb+f+"&napr="+b+": "+c.message;(new Image).src=e}catch(g){}}}};this.Cd=function(){try{if(this.dvObj&&this.impressionId&&this.dvObj.tags[this.impressionId]){var a=this;this.dvObj.tags[this.impressionId].getViewabilityData=function(){try{for(var b=a.c.ke().slice(0),c=0;c<b.length;c++)void 0===b[c]||null===b[c]?b[c]=0:isNaN(b[c])||(b[c]/=1E3);var e={};e.bucket_0=b[0];e.bucket_1_9=b[1];e.bucket_100=b[11];for(c=2;10>=c;c++)e["bucket_"+(10*(c-1)).toString()+"_"+(10*c-1).toString()]=b[c];return{buckets:e,
isAdMeasureable:a.Xb,totalPageTime:(a.c.jb()-a.c.ue())/1E3,notApplicableTime:a.c.Qc()/1E3}}catch(f){return{}}}}}catch(b){}};this.Dd=function(){try{if(this.dvObj&&this.impressionId&&this.dvObj.tags[this.impressionId]){var a=this.dvObj.tags[this.impressionId];a.VA||(a.VA={});a.VA.getVisibilityResult=function(){var a={};a.perc=p.i;0<=p.i&&p.L&&p.L.j&&(a.adWidth=p.L.j.o,a.adHeight=p.L.j.m);return a}}}catch(b){}};this.Cd();this.start=function(){this.b.a("s35");this.Ve(this);var a;this.ba&&this.ba.Ba&&
this.ba.Ba[this.Ya]&&(a=this.ba.Ba[this.Ya].Ia);if(a)for(var b=a.length,c=0;c<b;c++)this.fd[a[c]]=this.Rc(a[c]),this.Ga(this.window,a[c],this.fd[a[c]]);this.nf();this.ba&&this.ba.Ba&&this.ba.Ba[this.Ya]&&this.ba.Ba[this.Ya].qd&&setTimeout(this.$e(),this.ba.Ba[this.Ya].qd)};this.$e=function(){var a=this;return function(){a.Rc("timeout")();clearInterval(a.interval);a.U.sc=function(){};a.U.$=function(){}}};this.Ve=function(a){try{var b=a.cc(a);-5==b.i&&(this.c.md(),this.Ka||(this.Ka=function(b){b=a.ua.pb(b);
a.c.$a(b)}));if(a.Oa)if(this.uc=!0,-5!=b.i){var c=a.ua.pb(b);a.c.$a(c)}else a.c.$a("true");a.c.od(b.ea);var e=a.ua.he(b,a.c.Qc());a.c.hf(e);a.c.nd(b.i);a.zb(b);a.ab(b);a.Ma(a,b)}catch(f){a.Na(function(){a.Db("onStartReport",f);a.c.pc("onStartReport: "+f.message);a.U.$(a.c.ca(a.logEvents.errorlevel1),a.logEvents.errorlevel1)},"onStartReport",f)}};this.nf=function(){this.Ga(this.window,"blur",this.Ta());this.Ga(this.window,"focus",this.Ta());this.Ga(this.window.document,"click",this.Ta());this.Ga(this.window.document,
"mousedown",this.Ta());this.Ga(this.window.document,"mouseup",this.Ta())};this.Ga=function(){function a(b,c,e){a=b.addEventListener?function(a,b,c){a.addEventListener(b,c,!1)}:b.attachEvent?function(a,b,c){a.attachEvent("on"+b,c)}:function(a,b,c){a["on"+b]=c};a(b,c,e)}return function(b,c,e){a(b,c,e)}}();this.stop=function(){};this.lf=function(){this.b.a("ff24");this.M==this.X.CrossDomain?this.b.wa(this.window)||this.b.ic(this.window)||this.b.qb()||this.b.rb(this.M,this.I,this.dvObj)||(this.I.V!=this.W.Firefox&&
this.I.V!=this.W.IE?this.c.mf():this.I.V==this.W.Firefox&&"undefined"===typeof this.window.mozInnerScreenX&&this.c.qc()):window.document.body.getBoundingClientRect||this.c.qc();this.ec=this.c.Rb();this.b.a("ff24e")};this.Na=function(a,b,c){try{a()}catch(f){try{if(0<this.dd){this.dd--;var e=this.ga.protocol+this.ga.domain+this.ga.port+"/"+this.ga.api+"?"+this.T+"&ctime="+(new Date).getTime()+"&evid="+this.logEvents.errorlevel1+"&jsver="+this.Nb+this.b.mb()+"&napr="+(b||"unknown caller")+": "+(c||f).message;
(new Image).src=e}}catch(g){}}};return this}
try{window.dv_InViewService=dv_InViewService;dv_InViewService.prototype.inViewManager=dv_InViewService.prototype.inViewManager;var ViewAssureBootstrapper=function(h){$dv.tags[$uid].gmmod||$dv.tags[$uid].cvmSettings||$dv.tags[$uid].billable||h.cvmSettings||h.billable?(new dv_CustomClientViewAssureService(h)).inViewManager():(new dv_InViewService(h)).inViewManager()};if("function"===typeof window.IVCallback)IVCallback(ViewAssureBootstrapper);else for(var ka=[window.$dvbs,window.$dvbsr],Z=0;Z<ka.length;Z++){var dvObj=
ka[Z];if(dvObj&&"object"===typeof dvObj&&"function"===typeof dvObj.getTagObjectByService){var tagObject=dvObj.getTagObjectByService("avs611");if(tagObject){var serviceParams=tagObject.services.avs611;serviceParams&&serviceParams.params&&ViewAssureBootstrapper(serviceParams.params)}}}}catch(h){};
